variables:
  AZCOPY_GOLANG_VERSION: '1.25.11'
  AZCOPY_GOLANG_VERSION_COVERAGE: '1.25.11'

trigger:
  branches:
    include: [ 'main' ]

pr:
  branches:
    include: [ '*' ]

stages:
  - stage: Tests
    displayName: 'Build and test AzCopy'
    jobs:
      - template: azurePipelineTemplates/test-jobs.yml
