// Visual: Time chart
customMetrics
| where timestamp between (_startTime .. _endTime)
| where tostring(customDimensions.ServiceName) == 'azcopy'
| where name in (
    'azcopy.objects_scheduled',
    'azcopy.regular_files_scheduled',
    'azcopy.symlinks_scheduled',
    'azcopy.hardlinks_converted_scheduled',
    'azcopy.folder_properties_scheduled')
| summarize Objects = sum(value) by bin(timestamp, 1h), Metric = name
| order by timestamp asc