// Visual: Table or bar chart
customMetrics
| where timestamp between (_startTime .. _endTime)
| where name == 'azcopy.job.finished'
| where tostring(customDimensions.ServiceName) == 'azcopy'
| extend
    SourceType = tostring(customDimensions.SourceType),
    DestType = tostring(customDimensions.DestType),
    Topology = tostring(customDimensions.TransferTopology),
    HostOS = tostring(customDimensions.OSType),
    Version = tostring(customDimensions.ServiceVersion),
    SamplingRate = todouble(customDimensions.SamplingRate)
| extend Weight = iif(SamplingRate > 0.0 and SamplingRate <= 1.0, 1.0 / SamplingRate, 1.0)
| summarize
    ObservedAttempts = count(),
    EstimatedAttempts = sum(Weight)
  by SourceType, DestType, Topology, HostOS, Version
| top 30 by EstimatedAttempts desc
| project SourceType, DestType, Topology, HostOS, Version, ObservedAttempts, EstimatedAttempts = round(EstimatedAttempts, 0)